### ISSUE TITLE
Trigger manually?

### ISSUE THREAD

**Issue by jchannon** [Decathlon/release-notes-generator-action#14] opened 2020-09-06 16:52 UTC
With the new action [workflow_dispatch](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) I can trigger actions manually. Is there a way to pass in a milestone number to the release notes generator action so it generates release notes? Obvioulsy I could re-open then close a milestone but....

**Comment by mmornati** [comment] 2020-12-19 13:40
Hey. Sorry for the daly but that indeed a good idea.
I'm working on it right now.

**Comment by mmornati** [comment] 2020-12-19 14:30
PR ready and in review. 
All seems work. If you want to test it before the official release (need to wait for the review) you can doing it in this way:
```
on:
  milestone:
    types: [closed]
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'     
        required: true
        default: '1'
name: Milestone Closure
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Release Notes
        uses: decathlon/release-notes-generator-action@feat_workflow_dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: temp_release_notes
          USE_MILESTONE_TITLE: "true"
```

**Comment by jchannon** [comment] 2020-12-19 15:55
Cool. Will take a look over the holidays

**Comment by MysterAitch** [comment] 2021-01-02 13:25
PR has been merged - presumably this issue can be closed? Or is there more to come? :)

**Comment by BWPanda** [comment] 2021-01-05 10:23
This doesn't seem to work if you *only* want to run it manually, and not on milestone closure as well...

I get the following error:
```
Getting Action Information
Milestone number is missing. Was the action raised by a milestone event?
```

**Comment by nmbsd** [comment] 2021-01-08 06:33
I get the same issue as @BWPanda .
I did `docker pull decathlon/release-notes-generator-action:latest ` and confirmed that the necessary code changes have _not_ been applied and there's also no 3.1.0 tag on [Docker Hub](https://hub.docker.com/r/decathlon/release-notes-generator-action/tags?page=1&name=3.1.0)

**Comment by nmbsd** [comment] 2021-01-08 06:43
Never mind. Looks like Docker Hub is out of date but what is published to the GitHub Actions Marketplace is up-to-date. I can use:
```
- name: Create Release Notes
   uses: Decathlon/release-notes-generator-action@v3.1.0
```

**Comment by mmornati** [comment] 2021-01-29 21:45
Hey, guys sorry. I missed messages (too many notifications to follow every day).
I will try to update Dockerhub as it seems it is the one not updated. But I thought the build and publish was automatic.
@lusoalex can you confirm you configured everything to build the actions automatically.

**Closed** 2021-02-22 22:06 UTC
Labels: enhancement
